### ISSUE TITLE
Milestone One 

### ISSUE THREAD

**Issue by fobosmaker** [fobosmaker/rooteweb#1]
**1. User Management** (11 Oktober 2020 - 25 Oktober 2020)

- [ ] User dapat berinteraksi kedalam sistem seperti  membuat akun, lupa password, melihat dan merubah data profil, login dan logout

**2. GeoLocation** (26 Oktober 2020 - 26 November 2020)
- [ ] User dapat melakukan check in di setiap destinasi dalam trail

- [ ] User dapat melakukan proses live tracking selama berada dalam trail

- [ ] Sistem mampu memantau jumlah orang yang aktif di dalam sebuah trail

- [ ] Sistem mampu memberikan konfirmasi kesiapan protokol kesehatan selama era pandemi

**3. Social Interaction** (27 November 2020 - 3 Desember 2020)

- [ ] User dapat memberikan like pada trail

- [ ] User dapat melontarkan komentar dalam trail

- [ ] User dapat memberikan rating untuk sebuah trail

**4. Research Development** (4 Desember 2020 - 31 Desember 2020)

- [ ] User dapat membuat akun dengan akun gmail mereka

- [ ] User dapat membuat akun dengan akun facebook mereka

**5. Maintenance** (11 Oktober 2020 - 31 Desember 2020)
